In [1]:
import tensorflow as tf
import numpy as np
import pprint

In [2]:
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [3]:
# One hot encoding for each character in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [4]:
with tf.variable_scope('one_cell') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    print('cell output: ', cell.output_size, 'cell state: ', cell.state_size)
    
    x_data = np.array([[h]], dtype=np.float32)
    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

cell output:  2 cell state:  2
array([[[ 1.,  0.,  0.,  0.]]], dtype=float32)
array([[[ 0.17574091, -0.04733711]]], dtype=float32)


In [5]:
with tf.variable_scope('two_sequences') as scope:
    hidden_size = 2
    cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
    x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(1, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]], dtype=float32)
array([[[-0.37922981, -0.34277201],
        [ 0.41266534, -0.64213824],
        [-0.70156085, -0.29443604],
        [-0.70108694, -0.21941139],
        [-0.71391612, -0.14400788]]], dtype=float32)


In [7]:
with tf.variable_scope('3_batches') as scope:
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.04301316,  0.00422183],
        [ 0.14880131, -0.13143046],
        [ 0.28026578, -0.13792183],
        [ 0.34078047, -0.16065718],
        [ 0.12640949, -0.14173326]],

       [[ 0.12813665, -0.13857494],
        [-0.04166914, -0.07336584],
        [ 0.14380468, -0.12062025],
        [ 0.25681463, -0.15664572],
        [ 0.32478958, -0.17555331]],

       [[ 0.17859839, -0.08103026],
        [ 0.2819303 , -0.12608649],
        [ 0.25999355, -0.25370908],
        [ 0.27304298, -0.30985466],
        [ 0.3647278 ,

In [8]:
with tf.variable_scope('3_batches_dynamic_length') as scope:
    # One cell RNN input_dim (4) -> output_dim (5). sequence: 5, batch 3
    # 3 batches 'hello', 'eolll', 'lleel'
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(
        cell, x_data, sequence_length=[5,3,4], dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.01803977,  0.07359975],
        [-0.20562993,  0.02059694],
        [-0.0273429 ,  0.12786445],
        [ 0.0429509 ,  0.21085638],
        [-0.07613549,  0.12181748]],

       [[-0.20955224, -0.04234534],
        [-0.21718961, -0.01945081],
        [-0.06232519,  0.09599711],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[ 0.0693555 ,  0.14041021],
        [ 0.10895161,  0.22844833],
        [-0.11526101,  0.14751938],
        [-0.29728124,  0.06344642],
        [ 0.        ,

In [9]:
with tf.variable_scope('initial_state') as scope:
    batch_size = 3
    x_data = np.array([[h, e, l, l, o],
                      [e, o, l, l, l],
                      [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    # One cell RNN input_dim (4) -> output_dim (5). sequence: 5, batch: 3
    hidden_size=2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    
    # set initial state
    initial_state = cell.zero_state(batch_size, tf.float32)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data,
                                         initial_state=initial_state, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
array([[[ 0.05749469,  0.04692484],
        [ 0.0790806 ,  0.23149674],
        [ 0.07824627,  0.07173384],
        [ 0.05728013, -0.03345788],
        [-0.08006266, -0.11638235]],

       [[ 0.0306022 ,  0.17888345],
        [-0.07394359, -0.00494244],
        [-0.05971598, -0.10230546],
        [-0.07044675, -0.17292917],
        [-0.08768567, -0.22503065]],

       [[-0.01212858, -0.09394435],
        [-0.03420835, -0.16454957],
        [-0.00851936,  0.01633018],
        [ 0.02588198,  0.1906478 ],
        [ 0.03252143,