## Lab06 Softmax classifier

In [1]:
import tensorflow as tf
tf.set_random_seed(777)

In [2]:
# set data
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
# prepare placeholders
n_features = 4
n_classes = 3
X = tf.placeholder(tf.float32, [None, n_features])
Y = tf.placeholder(tf.float32, [None, n_classes])

In [5]:
W = tf.Variable(tf.random_normal([n_features, n_classes], name='weight'))
b = tf.Variable(tf.random_normal([n_classes], name='bias'))

In [6]:
# out hypothesis
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [7]:
# the cross entrophy loss
cost = tf.reduce_mean( -tf.reduce_sum(Y * tf.log(hypothesis), axis=1) )

In [8]:
# our optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [9]:
# start training
training_size = 2000
print_step = 200
with tf.Session() as sess:
    # initialize variables
    sess.run(tf.global_variables_initializer())
    
    for step in range(training_size):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % print_step == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
    
    # Testing & One-hot encoding
    print('--------------')
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.arg_max(a, 1)))
    
    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.arg_max(b, 1)))
    
    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.arg_max(c, 1)))
    
    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.arg_max(all, 1)))
    

0 10.8373
200 0.531087
400 0.430299
600 0.352601
800 0.277461
1000 0.236321
1200 0.21412
1400 0.195644
1600 0.180017
1800 0.166628
--------------
[[  1.00579429e-02   9.89935219e-01   6.84254792e-06]] [1]
--------------
[[ 0.80333501  0.18540043  0.01126456]] [0]
--------------
[[  8.65935235e-09   3.02491448e-04   9.99697566e-01]] [2]
--------------
[[  1.00579476e-02   9.89935219e-01   6.84256111e-06]
 [  8.03335011e-01   1.85400501e-01   1.12645645e-02]
 [  8.65935235e-09   3.02491448e-04   9.99697566e-01]] [1 0 2]
