In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
W = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")
hypothesis = tf.matmul(X, W) + b

In [5]:
# cost / loss
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-05)
train = optimizer.minimize(cost)

In [6]:
# start training
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        


0 Cost:  110442.0 
Prediction:
 [[-149.74220276]
 [-165.50102234]
 [-170.57775879]
 [-184.39910889]
 [-123.90067291]]
1000 Cost:  10.0249 
Prediction:
 [[ 146.49559021]
 [ 187.9440918 ]
 [ 179.03840637]
 [ 196.13534546]
 [ 145.19616699]]
2000 Cost:  6.07608 
Prediction:
 [[ 147.55488586]
 [ 187.22105408]
 [ 179.36701965]
 [ 196.34156799]
 [ 144.27397156]]
3000 Cost:  3.77149 
Prediction:
 [[ 148.36584473]
 [ 186.66824341]
 [ 179.61943054]
 [ 196.49343872]
 [ 143.57449341]]
4000 Cost:  2.42361 
Prediction:
 [[ 148.98728943]
 [ 186.24523926]
 [ 179.81367493]
 [ 196.60388184]
 [ 143.0447998 ]]
5000 Cost:  1.63244 
Prediction:
 [[ 149.46418762]
 [ 185.92126465]
 [ 179.96357727]
 [ 196.68296814]
 [ 142.64447021]]
6000 Cost:  1.1654 
Prediction:
 [[ 149.83079529]
 [ 185.67286682]
 [ 180.07957458]
 [ 196.73823547]
 [ 142.34272766]]
7000 Cost:  0.887212 
Prediction:
 [[ 150.11317444]
 [ 185.4821167 ]
 [ 180.16966248]
 [ 196.77540588]
 [ 142.11607361]]
8000 Cost:  0.719186 
Prediction:
 [[ 150.