In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y  = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name="weight1")
w2 = tf.Variable(tf.random_normal([1]), name="weight2")
w3 = tf.Variable(tf.random_normal([1]), name="weight3")
b = tf.Variable(tf.random_normal([1]), name="bias")
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [5]:
# cost / loss
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-05)
train = optimizer.minimize(cost)

In [8]:
# start training
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(20001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
        if step % 1000 == 0:
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        


0 Cost:  2871.58 
Prediction:
 [ 111.87011719  122.68323517  127.07879639  134.35946655   94.41945648]
1000 Cost:  13.4032 
Prediction:
 [ 157.68774414  180.67071533  182.69165039  195.15995789  139.1764679 ]
2000 Cost:  8.48416 
Prediction:
 [ 156.49992371  181.47880554  182.31973267  194.95246887  140.18501282]
3000 Cost:  5.59315 
Prediction:
 [ 155.58802795  182.0978241   182.032547    194.80480957  140.94668579]
4000 Cost:  3.88299 
Prediction:
 [ 154.88674927  182.57266235  181.81007385  194.7026062   141.52033997]
5000 Cost:  2.86101 
Prediction:
 [ 154.34620667  182.93743896  181.63702393  194.63475037  141.95072937]
6000 Cost:  2.24046 
Prediction:
 [ 153.92831421  183.21824646  181.50175476  194.59286499  142.27198792]
7000 Cost:  1.85466 
Prediction:
 [ 153.60414124  183.43496704  181.39538574  194.57058716  142.51028442]
8000 Cost:  1.60662 
Prediction:
 [ 153.35159302  183.60270691  181.31111145  194.56297302  142.68540955]
9000 Cost:  1.43973 
Prediction:
 [ 153.15376282 