In [1]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)

pp = pprint.PrettyPrinter(indent=4)

## 1D Array

In [2]:
t1 = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t1)
print(t1.ndim) # rank
print(t1.shape) # shape
print(t1[0], t1[1], t1[-1])
print(t1[2:5], t1[4:-1]) # [포함:미포함]
print(t1[:2], t1[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


## 2D array

In [3]:
t2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t2)
print(t2.ndim) # rank
print(t2.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


## Shape, Rank, Axis

In [4]:
sess = tf.InteractiveSession()

In [5]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [6]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [7]:
t = tf.constant([[[[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]],
                  [[13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [8]:
[ # axis = 0
    [ # axis = 1
        [ # axis = 2
            [1,2,3,4], # axis = 3 == axis = -1 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul vs multiply

In [9]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(tf.shape(matrix1).eval())
print(tf.shape(matrix2).eval())
print(tf.matmul(matrix1, matrix2).eval())

[1 2]
[2 1]
[[ 12.]]


In [10]:
print((matrix1*matrix2).eval())

[[ 6.  6.]
 [ 6.  6.]]


## Broadcasting??
Broadcating: operation can be done without error even though the shapes doesn't match!! 

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [12]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.) # becomes [[3., 3.]] via broadcasting
(matrix1+matrix2).eval()

array([[ 4.,  5.]], dtype=float32)

In [13]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

## Random values for variable initializations

In [14]:
tf.random_normal([3]).eval()

array([-0.42033267, -0.48115173,  0.49280021], dtype=float32)

In [15]:
tf.random_uniform([2]).eval()

array([ 0.81213546,  0.41717839], dtype=float32)

In [16]:
tf.random_uniform([2, 3]).eval()

array([[ 0.21788406,  0.95766389,  0.17695117],
       [ 0.570315  ,  0.60460925,  0.19412613]], dtype=float32)

## Reduce Mean/Sum

In [17]:
tf.reduce_mean([1, 2], axis=0).eval() # integer will outputs integer...

1

In [18]:
tf.reduce_mean([1., 2.], axis=0).eval()

1.5

In [19]:
x = [[1., 2.],
     [3., 4.]]

In [20]:
tf.reduce_mean(x).eval()

2.5

In [21]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [22]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [23]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [24]:
tf.reduce_sum(x).eval()

10.0

In [25]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [26]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [27]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis

In [28]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [29]:
tf.argmax(x, axis=0).eval() # index of maximum value

array([1, 0, 0], dtype=int64)

In [30]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [31]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape, squeeze, expand_dims

In [32]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])

In [33]:
t.shape

(2, 2, 3)

In [34]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [36]:
tf.squeeze([[0], [1], [2]]).eval() # squeeze dimension

array([0, 1, 2])

In [37]:
tf.squeeze([[[0], [1], [2]]]).eval()

array([0, 1, 2])

In [38]:
tf.expand_dims([0, 1, 2], 1).eval() # expand dimension

array([[0],
       [1],
       [2]])

## One hot
* tf.one_hot() will increase rank by 1
* should we reshape after one hot

In [39]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval() # 3 classes

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [40]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

## casting

In [41]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [42]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

In [43]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

In [44]:
# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like and Zeros like

In [47]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [48]:
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [49]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip

In [50]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [51]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [52]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [53]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [54]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [55]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [56]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
